<?php

function shift_cipher_menu() {
    $items = array();
    $items['shift_cipher'] = array(
        'title' => 'Shift Cipher',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('shift_cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['shift_cipher_success_page'] = array(
        'title' => 'Success',
        'page callback' => 'shift_cipher_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function shift_cipher_form() {
    $form['shift_value'] = array(
        '#title' => 'Shift Value',
        '#type' => 'textfield',
        '#description' => t('Please enter a shifting value'),
        '#element_validate' => array('element_validate_range'),
        '#required' => TRUE,
    );
    $form['shift_direction'] = array(
        '#title' => 'Shift direction',
        '#type' => 'textfield',
        '#description' => t('Please enter a shifting direction (left or right)'),
        '#element_validate' => array('element_validate_direction'),
        '#required' => TRUE,
    );
    $form['phrase'] = array(
        '#title' => 'Phrase',
        '#type' => 'textfield',
        '#description' => t('Please enter a Phrase'),
        '#required' => TRUE,
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encyrpt!',
    );

    return $form;
}

function element_validate_range($element) {
    if ($element['#value'] > 26 || $element['#value'] < 1) {
        form_error($element, t('Number must be less than 26 or greater than 1.'));
    }
}

function element_validate_direction($element) {
    if((!$element['#value'] == 'left') || (!$element['#value'] == 'right')) {
        form_error($element, t('The direction must be left or right..'));
    }
}

function shift_cipher_form_submit($form, &$form_state) {
    $value = $form_state['values']['shift_value'];
    $direction = strtolower($form_state['values']['shift_direction']);
    $phrase = strtolower($form_state['values']['phrase']);

    if(strtolower($direction) == 'left') {
        $value = $value * -1;
    }

    $split_phrase = str_split($phrase, 1);

    $alphabet = array('a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z');

    foreach($split_phrase as &$letter) {
        if(in_array($letter, $alphabet)) {
            $index = array_search($letter, $alphabet) + $value;

            if($index > 25) {
                $index = $index - 26;
            } elseif($index < 0) {
                $index = $index + 26;
            } else {
                $letter = $alphabet[$index];
            }
        }
    }

    $output = implode('', $split_phrase);
    $_SESSION['encyrption_success_output'] = $output;
    $form_state['redirect'] = 'shift_cipher_success_page';
}

function shift_cipher_success() {
    return $_SESSION['encyrption_success_output'];
}
